version: "3.3"
services:
  flask_api:
    build:
      context: ./api-server-flask
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./api-server-flask:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  client:
    depends_on:
      - flask_api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

    volumes:
      - ./client/src:/app/src

    environment:
      - WATCHPACK_POLLING=true

