version: '3.3'

# x-common-variables: &common-variables
#   MYSQL_DATABASE: parcity
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  # mysql_db:
  #   image: mysql
  #   restart: always
  #   cap_add:
  #     - SYS_NICE
  #   volumes:
  #     - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"   dont know if this is necessary (maybe add volume to cloud sql server)
  #   ports:
  #     - "9906:3306"
  #   environment:
  #     <<: *common-variables
  #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
  #     MYSQL_HOST: localhost
  nginx:
    image: nginx
    depends_on:
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - client:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    links:
      - "client"

  client:
    build: ./client
      # dockerfile: Dockerfile
      # context: ./client
    volumes:
      - client/:/usr/share/nginx/html
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    


      # - /app/node_modules
      # - ./client:/app
      #
      #
volumes:
  client:
