version: "3.3"
services:
  flask_api:
    build:
      context: ./api-server-flask
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./api-server-flask:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

      # change sqlalchemy string to postgres service 
      # - DATABASE_URL=sqlite:///app/api/apidata.db
      - DATABASE_URL=postgresql://test:test@db:5432/test
      - SECRET_KEY="flask-app-secret-key"
      - JWT_SECRET_KEY="jwt-app-secret-key"
    depends_on:
      - db

  client:
    depends_on:
      - flask_api
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

    volumes:
      - ./client/src:/app/src

    environment:
      - WATCHPACK_POLLING=true
  
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:alpine
    networks:
      - default
    ports:
      - 5405:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  db:
    driver: local
