version: '3.3'

# x-common-variables: &common-variables
#   MYSQL_DATABASE: parcity
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  # mysql_db:
  #   image: mysql
  #   restart: always
  #   cap_add:
  #     - SYS_NICE
  #   volumes:
  #     - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"   dont know if this is necessary (maybe add volume to cloud sql server)
  #   ports:
  #     - "9906:3306"
  #   environment:
  #     <<: *common-variables
  #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
  #     MYSQL_HOST: localhost
  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
